const bookmarks = [
  { url: "https://dribbble.com/shots", tags: ["inspiration"] },
  { url: "https://www.pinterest.fr/", tags: ["inspiration"] },
  { url: "https://gitsheet.wtf/", tags: ["cheatsheet"] },
  { url: "https://html5doctor.com/element-index/#v", tags: ["cheatsheet"] },
  { url: "https://devhints.io/", tags: ["cheatsheet"] },
  { url: "https://www.justinaguilar.com/animations", tags: ["cheatsheet"] },
  { url: "https://alialaa.github.io/css-grid-cheat-sheet/", tags: ["cheatsheet"] },
  { url: "https://grid.malven.co/", tags: ["cheatsheet"] },
  { url: "https://easings.net/en#", tags: ["cheatsheet"] },
  { url: "https://mac-blog.org.ua/css-3-media-queries-cheat-sheet", tags: ["cheatsheet"] },
  { url: "https://simon.html5.org/dump/html5-canvas-cheat-sheet.html", tags: ["cheatsheet"] },
  { url: "https://moz.com/learn/seo/seo-cheat-sheet", tags: ["cheatsheet"] },
  { url: "https://mbeaudru.github.io/modern-js-cheatsheet/", tags: ["cheatsheet"] },
  { url: "https://html5sec.org/", tags: ["cheatsheet"] },
  { url: "https://apps.workflower.fi/vocabs/html/en#children", tags: ["cheatsheet"] },
  { url: "https://dev.to/emmabostian/regex-cheat-sheet-2j2a", tags: ["cheatsheet"] },
  { url: "https://www.larevuedesressources.org/le-manifeste-du-hacker,2298.html", tags: ["cheatsheet"] },
  { url: "https://feathericons.com/", tags: ["icons", "SVG"] },
  { url: "https://heroicons.com/", tags: ["icons", "SVG"] },
  { url: "https://icones.js.org/", tags: ["icons", "SVG"] },
  { url: "https://iconoir.com/", tags: ["icons", "SVG"] },
  { url: "https://www.reshot.com/", tags: ["icons", "SVG"] },
  { url: "https://svgcrop.com/", tags: ["icons", "SVG"] },
  { url: "https://svgfilters.com/", tags: ["icons", "SVG"] },
  { url: "https://www.freepik.com/", tags: ["icons", "SVG"] },
  { url: "https://feathericons.com/?query=linke", tags: ["icons", "SVG"] },
  { url: "https://www.flaticon.com/", tags: ["icons", "SVG"] },
  { url: "https://favpng.com/", tags: ["images"] },
  { url: "https://pngimg.com/", tags: ["images"] },
  { url: "https://purepng.com/", tags: ["images"] },
  { url: "https://www.stickpng.com/fr", tags: ["images"] },
  { url: "https://www.cleanpng.com/", tags: ["images"] },
  { url: "https://www.pexels.com/fr-fr/", tags: ["images"] },
  { url: "https://unsplash.com/", tags: ["images"] },
  { url: "https://www.blogduwebdesign.com/image-png-gratuite", tags: ["images"] },
  { url: "https://unsplash.com/", tags: ["images"] },
  { url: "https://gitlab.com/lydra/legal", tags: ["legal"] },
  { url: "https://github.com/jagenjo/litegraph.js", tags: ["librairie", "javascript"] },
  { url: "https://www.npmjs.com/package/uuid", tags: ["librairie", "javascript"] },
  { url: "https://www.npmjs.com/package/moment", tags: ["librairie", "javascript"] },
  { url: "https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-fr.md", tags: ["livres"] },
  { url: "https://goalkicker.com/", tags: ["livres"] },
  { url: "https://www.syncfusion.com/succinctly-free-ebooks", tags: ["livres"] },
  { url: "http://www.cheeseipsum.co.uk/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://slipsum.com/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://lipsum.com/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://developers.google.com/web/tools/lighthouse/", tags: ["Outil"] },
  { url: "https://imageonline.co/case-converter-fr.php", tags: ["Outil"] },
  { url: "https://dbdiagram.io/home", tags: ["Outil"] },
  { url: "https://cssflex-generator.netlify.app/", tags: ["Outil"] },
  { url: "https://www.jesuisundev.com/20-Outils-webs/", tags: ["Outil"] },
  { url: "https://jsonformatter.curiousconcept.com/#", tags: ["Outil"] },
  { url: "https://cssbattle.dev", name: "CSS Battle", description: "Use your CSS skills to replicate targets with smallest possible code.", tags: ["challenge"] },
  { url: "http://flukeout.github.io", name: "CSS Diner", description: "Where we feast on CSS Selectors! (Apprendre les selecteurs CSS", tags: ["challenge"] },
  { url: "https://jgthms.com", name: "Jt is a CSS guru", tags: ["challenge"] },
  { url: "https://any-api.com", "name": "Any-api.com", description: "Documentation and Test Consoles for Over 1400 Public APIs", tags: ["API Public"] },
  { url: "https://cssgradient.io", name: "CSS Gradient", description: "Generator, Maker, and Background", tags: ["CSS", Dégradé] },
  { url: "https://forqrcode.com", name: "Free QR Code Generator", description: "Free QR Code Generator in SVG, EPS, PNG", tags: ["Generateur", "QR Code"] },
  { url: "https://showcode.app/", tags: ["Outil"] },
  { url: "https://yqnn.github.io/svg-path-editor/", tags: ["Outil"] },
  { url: "https://Outils-javascript.aliasdmc.fr/encodage-caracteres-speciaux/encode-caractere-2022-html-css-js-autre.html", tags: ["Outil"] },
  { url: "http://compteur-de-mots.net/", tags: ["Outil"] },
  { url: "https://cssgradient.io/", tags: ["Outil"] },
  { url: "https://www.sejda.com/", tags: ["Outil"] },
  { url: "https://textcaseconvert.com/uuid-generator/fr", tags: ["Outil"] },
  { url: "https://www.w3schools.io/file/markdown-images/", tags: ["Outil"] },
  { url: "https://www.larevuedesressources.org/le-manifeste-du-hacker,2298.html", tags: ["Outil"] },
  { url: "https://emojipedia.org/", tags: ["Outil"] },
  { url: "https://codeconvey.com/", tags: ["Outil"] },
  { url: "https://getcssscan.com/css-box-shadow-examples", tags: ["Outil"] },
  { url: "https://flaviocopes.com/acronyms-web-development/", tags: ["Outil"] },
  { url: "http://rapid-application-development-js.github.io/AnimateTransition/popups.html", tags: ["Outil"] },
  { url: "https://unsplash.com/s/photos/architecture-green", tags: ["Outil"] },
  { url: "https://lecoupa.github.io/awesome-cheatsheets/", tags: ["Outil"] },
  { url: "http://bada55.io/", tags: ["Outil"] },
  { url: "https://bootswatch.com/sketchy/", tags: ["Outil"] },
  { url: "https://cleanup.pictures/", tags: ["Outil"] },
  { url: "https://codebeautify.org/", tags: ["Outil"] },
  { url: "https://webcode.tools/generators/css/box-resize", tags: ["Outil"] },
  { url: "https://cssbuttons.app/", tags: ["Outil"] },
  { url: "https://alialaa.github.io/css-grid-cheat-sheet/", tags: ["Outil"] },
  { url: "https://excalidraw.com/", tags: ["Outil"] },
  { url: "https://realfavicongenerator.net/", tags: ["Outil"] },
  { url: "https://flexboxpatterns.com/", tags: ["Outil"] },
  { url: "https://codepen.io/enxaneta/full/adLPwv/", tags: ["Outil"] },
  { url: "https://www.flaticon.com/authors/freepik", tags: ["Outil"] },
  { url: "https://www.flaticon.com/authors/pixel-perfect", tags: ["Outil"] },
  { url: "https://q-r-code.fr/", tags: ["Outil"] },
  { url: "https://getwaves.io/", tags: ["Outil"] },
  { url: "https://gitmoji.dev/", tags: ["Outil"] },
  { url: "https://monkeytype.com/", tags: ["Outil"] },
  { url: "https://www.behance.net/", tags: ["Outil"] },
  { url: "https://www.unscreen.com/", tags: ["Outil"] },
  { url: "https://serviceworkies.com/", tags: ["Outil"] },
  { url: "https://silentteacher.toxicode.fr/", tags: ["Outil"] },
  { url: "https://storyset.com/", tags: ["Outil"] },
  { url: "https://webcode.tools/", tags: ["Outil"] },
  { url: "https://timestamp-tool.fr/", tags: ["Outil"] },
  { url: "https://www.timestamp.fr/?", tags: ["Outil"] },
  { url: "https://www.tldraw.com/", tags: ["Outil"] },
  { url: "https://www.tutomarks.fr/", tags: ["Outil"] },
  { url: "https://www.vectary.com/", tags: ["Outil"] },
  { url: "https://www.yacreader.com/", tags: ["Outil"] },
  { url: "https://free3dicon.com/", tags: ["Outil"] },
  { url: "https://quantumai.google/education/thequbitgame", tags: ["Outil"] },
  { url: "https://www.blogduwebdesign.com/image-png-gratuite", tags: ["Outil"] },
  { url: "https://www.blogduwebdesign.com/telecharger-fonds-ecran-wallpaper", tags: ["Outil"] },
  { url: "https://www.blogduwebdesign.com/illustrations-gratuites", tags: ["Outil"] },
  { url: "https://vectr.com/", tags: ["Outil"] },
  { url: "https://www.free-css.com/", tags: ["Outil", "Templates"] },
  { url: "https://startbootstrap.com/", tags: ["Outil", "Templates"] },
  { url: "https://www.template.net/", tags: ["Outil", "Templates"] },
  { url: "https://css-speedrun.netlify.app/", tags: ["Outil", "Templates"] },
  { url: "https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md", tags: ["Outil", "Templates"] },
  { url: "https://medium.com/@ti_asif/200-best-free-tools-resources-for-front-end-web-developers-3fb3c415a643", tags: ["Outil", "Templates"] },
  { url: "https://free-for.dev/#/", tags: ["Outil", "Templates"] },
  { url: "https://freefrontend.com/", tags: ["Outil", "Templates"] },
  { url: "http://gameaboutsquares.com/", tags: ["Outil", "Templates"] },
  { url: "https://www.gatsbyjs.com/plugins?utm_source=starter&utm_medium=start-page&utm_campaign=minimal-starter", tags: ["Outil", "Templates"] },
  { url: "https://www.goodemailcopy.com/", tags: ["Outil", "Templates"] },
  { url: "https://github.com/graphql/graphql-js", tags: ["Outil", "Templates"] },
  { url: "https://transform.tools/json-to-mongoose", tags: ["Outil", "Templates"] },
  { url: "https://riptutorial.com/", tags: ["Outil", "Templates"] },
  { url: "https://fffuel.co/llline/", tags: ["Outil", "Templates"] },
  { url: "https://www.loom.com/", tags: ["Outil", "Templates"] },
  { url: "https://ohshitgit.com/", tags: ["Outil", "Templates"] },
  { url: "https://openmoji.org/", tags: ["Outil", "Templates"] },
  { url: "https://overapi.com/", tags: ["Outil", "Templates"] },
  { url: "https://www.ssi.gouv.fr/particulier/bonnes-pratiques/poste-de-travail-et-serveurs/", tags: ["Outil", "Templates"] },
  { url: "https://minocernota.com/articles/pure_css_game/", tags: ["Outil", "Templates"] },
  { url: "https://unsplash.com/fr", tags: ["Outil", "Templates"] },
  { url: "https://phind.com/", tags: ["Outil", "Templates"] },
  { url: "https://quickref.me/", tags: ["Outil", "Templates"] },
  { url: "https://unminify.com/", tags: ["Outil", "Templates"] },
  { url: "https://favicon.io/", tags: ["Outil", "Templates"] },
  { url: "https://picsum.photos/", tags: ["Outil", "Templates"] },
  { url: "https://www.remove.bg/fr", tags: ["Outil", "Templates"] },
  { url: "https://pfpmaker.com/", tags: ["Outil", "Templates"] },
  { url: "https://compressor.io/", tags: ["Outil", "Templates"] },
  { url: "https://cssgradient.io/gradient-backgrounds/", tags: ["Outil", "Templates"] },
  { url: "https://neumorphism.io/#e0e0e0", tags: ["Outil", "Templates"] },
  { url: "https://animista.net/", tags: ["Outil", "Templates"] },
  { url: "https://fontjoy.com/", tags: ["Outil", "Templates"] },
  { url: "https://logoipsum.com/", tags: ["Outil", "Templates"] },
  { url: "https://carbon.now.sh/", tags: ["Outil", "Templates"] },
  { url: "https://browserframe.com/", tags: ["Outil", "Templates"] },
  { url: "https://box-shadow.dev/", tags: ["Outil", "Templates"] },
  { url: "https://readme.so/fr", tags: ["Outil", "Templates"] },
  { url: "https://metatags.io/", tags: ["Outil", "Templates"] },
  { url: "https://tinywow.com/", tags: ["Outil", "Templates"] },
  { url: "https://slidesgo.com/", tags: ["Outil", "Templates"] },
  { url: "https://imglarger.com/", tags: ["Outil", "Templates"] },
  { url: "https://o-dan.net/en/", tags: ["Outil", "Templates"] },
  { url: "https://regexr.com/", tags: ["Outil", "Templates"] },
  { url: "https://www.useblackbox.io/landingPage", tags: ["Outil", "Templates"] },
  { url: "https://www.docker.com/play-with-docker/", tags: ["Outil", "Templates"] },
  { url: "https://www.flaticon.com/", tags: ["Outil", "Templates"] },
  { url: "https://flathub.org/home", tags: ["Outil", "Templates"] },
  { url: "https://danielyxie.github.io/bitburner/", tags: ["Outil", "Templates"] },
  { url: "https://smalldev.tools/", tags: ["Outil", "Templates"] },
  { url: "https://smartmockups.com/fr", tags: ["Outil", "Templates"] },
  { url: "https://www.abandonware-magazines.org/affiche_mag.php?mag=304&page=1", tags: ["Outil", "Templates"] },
  { url: "https://pocketserver.org/#download", tags: ["Outil", "Templates"] },
  { url: "https://archive.org/", tags: ["Outil", "Templates"] },
  { url: "https://inkscape.org/forums/francais/", tags: ["Outil", "Templates"] },
  { url: "https://www.npmjs.com/package/@mdx-js/react", tags: ["Outil", "Templates"] },
  { url: "https://fffuel.co/", tags: ["Outil", "Templates"] },
  { url: "https://cheatography.com/programming/	", tags: ["Outil", "Cheatsheet"] },
  { url: "https://roadmap.sh", tags: ["Outil", "Roadmap"] },
  { url: "https://tinywow.com", tags: ["Outil"] },
  { url: "https://www.opensourcealternative.to", tags: ["Outil", "OpenSource", "Alternative"] },
  { url: "https://flowcv.com", tags: ["Outil", "CV"] },
  { url: "https://codebeautify.org", tags: ["Outil"] },
  { url: "https://explainshell.com", tags: ["Outil", "Shell"] },
  { url: "https://hexcolor.co/gradient-generator", tags: ["Outil", "Templates"] }
]
