const bookmarks = [
  { url: "https://dribbble.com/shots", tags: ["inspiration"] },
  { url: "https://www.pinterest.fr/", tags: ["inspiration"] },
  { url: "https://gitsheet.wtf/", tags: ["cheatsheet"] },
  { url: "https://html5doctor.com/element-index/#v", tags: ["cheatsheet"] },
  { url: "https://devhints.io/", tags: ["cheatsheet"] },
  { url: "https://www.justinaguilar.com/animations", tags: ["cheatsheet"] },
  { url: "https://alialaa.github.io/css-grid-cheat-sheet/", tags: ["cheatsheet"] },
  { url: "https://grid.malven.co/", tags: ["cheatsheet"] },
  { url: "https://easings.net/en#", tags: ["cheatsheet"] },
  { url: "https://mac-blog.org.ua/css-3-media-queries-cheat-sheet", tags: ["cheatsheet"] },
  { url: "https://simon.html5.org/dump/html5-canvas-cheat-sheet.html", tags: ["cheatsheet"] },
  { url: "https://moz.com/learn/seo/seo-cheat-sheet", tags: ["cheatsheet"] },
  { url: "https://mbeaudru.github.io/modern-js-cheatsheet/", tags: ["cheatsheet"] },
  { url: "https://html5sec.org/", tags: ["cheatsheet"] },
  { url: "https://apps.workflower.fi/vocabs/html/en#children", tags: ["cheatsheet"] },
  { url: "https://dev.to/emmabostian/regex-cheat-sheet-2j2a", tags: ["cheatsheet"] },
  { url: "https://www.larevuedesressources.org/le-manifeste-du-hacker,2298.html", tags: ["cheatsheet"] },
  { url: "https://feathericons.com/", tags: ["icons", "SVG"] },
  { url: "https://heroicons.com/", tags: ["icons", "SVG"] },
  { url: "https://icones.js.org/", tags: ["icons", "SVG"] },
  { url: "https://iconoir.com/", tags: ["icons", "SVG"] },
  { url: "https://www.reshot.com/", tags: ["icons", "SVG"] },
  { url: "https://svgcrop.com/", tags: ["icons", "SVG"] },
  { url: "https://svgfilters.com/", tags: ["icons", "SVG"] },
  { url: "https://www.freepik.com/", tags: ["icons", "SVG"] },
  { url: "https://feathericons.com/?query=linke", tags: ["icons", "SVG"] },
  { url: "https://www.flaticon.com/", tags: ["icons", "SVG"] },
  { url: "https://favpng.com/", tags: ["images"] },
  { url: "https://pngimg.com/", tags: ["images"] },
  { url: "https://purepng.com/", tags: ["images"] },
  { url: "https://www.stickpng.com/fr", tags: ["images"] },
  { url: "https://www.cleanpng.com/", tags: ["images"] },
  { url: "https://www.pexels.com/fr-fr/", tags: ["images"] },
  { url: "https://unsplash.com/", tags: ["images"] },
  { url: "https://www.blogduwebdesign.com/image-png-gratuite", tags: ["images"] },
  { url: "https://unsplash.com/", tags: ["images"] },
  { url: "https://gitlab.com/lydra/legal", tags: ["legal"] },
  { url: "https://github.com/jagenjo/litegraph.js", tags: ["librairie", "javascript"] },
  { url: "https://www.npmjs.com/package/uuid", tags: ["librairie", "javascript"] },
  { url: "https://www.npmjs.com/package/moment", tags: ["librairie", "javascript"] },
  { url: "https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-fr.md", tags: ["livres"] },
  { url: "https://goalkicker.com/", tags: ["livres"] },
  { url: "https://www.syncfusion.com/succinctly-free-ebooks", tags: ["livres"] },
  { url: "http://www.cheeseipsum.co.uk/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://slipsum.com/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://lipsum.com/", tags: ["lorem ipsum", "generateur"] },
  { url: "https://developers.google.com/web/tools/lighthouse/", tags: ["outil"] },
  { url: "https://imageonline.co/case-converter-fr.php", tags: ["outil"] },
  { url: "https://dbdiagram.io/home", tags: ["outil"] },
  { url: "https://cssflex-generator.netlify.app/", tags: ["outil"] },
  { url: "https://www.jesuisundev.com/20-outils-webs/", tags: ["outil"] },
  { url: "https://jsonformatter.curiousconcept.com/#", tags: ["outil"] },
  { url: "https://cssbattle.dev", name: "CSS Battle", description: "Use your CSS skills to replicate targets with smallest possible code.", tags: ["challenge"] },
  { url: "http://flukeout.github.io", name: "CSS Diner", description: "Where we feast on CSS Selectors! (Apprendre les selecteurs CSS", tags: ["challenge"] },
  { url: "https://jgthms.com", name: "Jt is a CSS guru", tags: ["challenge"] },
  { url: "https://any-api.com", "name": "Any-api.com", description: "Documentation and Test Consoles for Over 1400 Public APIs", tags: ["API Public"] },
  { url: "https://cssgradient.io", name: "CSS Gradient", description: "Generator, Maker, and Background", tags: ["CSS", Dégradé] },
  { url: "https://forqrcode.com", name: "Free QR Code Generator", description: "Free QR Code Generator in SVG, EPS, PNG", tags: ["Generateur", "QR Code"] },
]
